#application-name: simple-rag-app
#spring:
#    main:
#        web-application-type: none

client-openai-key: ${OPENAI_KEY}
client-openai-endpoint: https://ai-proxy.lab.epam.com/
client-openai-deployment-name: gpt-35-turbo